# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/GoogleCloudPlatform/guest-agent
%global goipath         github.com/GoogleCloudPlatform/guest-agent
Version:                20201217.02
%global tag             20201217.02

%gometa

%global common_description %{expand:
# FIXME}

%global golicenses      LICENSE\\\
                        THIRD_PARTY_LICENSES/google.golang.org/grpc/LICENSE T\\\
                        HIRD_PARTY_LICENSES/google.golang.org/genproto/LICENS\\\
                        E THIRD_PARTY_LICENSES/google.golang.org/api/LICENSE \\\
                        THIRD_PARTY_LICENSES/google.golang.org/protobuf/LICEN\\\
                        SE\\\
                        THIRD_PARTY_LICENSES/github.com/tarm/serial/LICENSE\\\
                        THIRD_PARTY_LICENSES/github.com/googleapis/gax-\\\
                        go/v2/LICENSE THIRD_PARTY_LICENSES/github.com/golang/\\\
                        groupcache/lru/LICENSE THIRD_PARTY_LICENSES/github.co\\\
                        m/golang/protobuf/LICENSE\\\
                        THIRD_PARTY_LICENSES/github.com/google/go-\\\
                        cmp/cmp/LICENSE THIRD_PARTY_LICENSES/github.com/go-\\\
                        ini/ini/LICENSE THIRD_PARTY_LICENSES/github.com/Googl\\\
                        eCloudPlatform/guest-agent/google_guest_agent/LICENSE\\\
                        THIRD_PARTY_LICENSES/github.com/GoogleCloudPlatform/g\\\
                        uest-logging-go/logger/LICENSE THIRD_PARTY_LICENSES/g\\\
                        ithub.com/kardianos/service/LICENSE\\\
                        THIRD_PARTY_LICENSES/cloud.google.com/go/LICENSE THIR\\\
                        D_PARTY_LICENSES/cloud.google.com/go/storage/LICENSE \\\
                        THIRD_PARTY_LICENSES/cloud.google.com/go/logging/LICE\\\
                        NSE THIRD_PARTY_LICENSES/go.opencensus.io/LICENSE\\\
                        THIRD_PARTY_LICENSES/golang.org/x/oauth2/LICENSE\\\
                        THIRD_PARTY_LICENSES/golang.org/x/sys/LICENSE\\\
                        THIRD_PARTY_LICENSES/golang.org/x/text/LICENSE\\\
                        THIRD_PARTY_LICENSES/golang.org/x/net/LICENSE THIRD_P\\\
                        ARTY_LICENSES/golang.org/x/sync/semaphore/LICENSE
%global godocs          CONTRIBUTING.md README.md packaging/debian/changelog

Name:           %{goname}
Release:        1%{?dist}
Summary:        None

# Upstream license specification: BSD-3-Clause and Apache-2.0 and Zlib
License:        BSD and ASL 2.0 and zlib
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(cloud.google.com/go/storage)
BuildRequires:  golang(github.com/go-ini/ini)
BuildRequires:  golang(github.com/golang/groupcache/lru)
BuildRequires:  golang(github.com/golang/protobuf/proto)
BuildRequires:  golang(github.com/GoogleCloudPlatform/guest-logging-go/logger)
BuildRequires:  golang(github.com/kardianos/service)
BuildRequires:  golang(github.com/tarm/serial)
BuildRequires:  golang(google.golang.org/grpc)
BuildRequires:  golang(google.golang.org/grpc/codes)
BuildRequires:  golang(google.golang.org/grpc/status)

%description
%{common_description}

%gopkg

%prep
%goprep

# Skip wsfc_test.go, which assumes that network is available.
rm google_guest_agent/wsfc_test.go

%build
for cmd in google_guest_agent google_metadata_script_runner; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check

%gocheck
%endif

%files
%license LICENSE THIRD_PARTY_LICENSES/google.golang.org/grpc/LICENSE
%license THIRD_PARTY_LICENSES/google.golang.org/genproto/LICENSE
%license THIRD_PARTY_LICENSES/google.golang.org/api/LICENSE
%license THIRD_PARTY_LICENSES/google.golang.org/protobuf/LICENSE
%license THIRD_PARTY_LICENSES/github.com/tarm/serial/LICENSE
%license THIRD_PARTY_LICENSES/github.com/googleapis/gax-go/v2/LICENSE
%license THIRD_PARTY_LICENSES/github.com/golang/groupcache/lru/LICENSE
%license THIRD_PARTY_LICENSES/github.com/golang/protobuf/LICENSE
%license THIRD_PARTY_LICENSES/github.com/google/go-cmp/cmp/LICENSE
%license THIRD_PARTY_LICENSES/github.com/go-ini/ini/LICENSE
%license THIRD_PARTY_LICENSES/github.com/GoogleCloudPlatform/guest-agent/google_guest_agent/LICENSE
%license THIRD_PARTY_LICENSES/github.com/GoogleCloudPlatform/guest-logging-go/logger/LICENSE
%license THIRD_PARTY_LICENSES/github.com/kardianos/service/LICENSE
%license THIRD_PARTY_LICENSES/cloud.google.com/go/LICENSE
%license THIRD_PARTY_LICENSES/cloud.google.com/go/storage/LICENSE
%license THIRD_PARTY_LICENSES/cloud.google.com/go/logging/LICENSE
%license THIRD_PARTY_LICENSES/go.opencensus.io/LICENSE
%license THIRD_PARTY_LICENSES/golang.org/x/oauth2/LICENSE
%license THIRD_PARTY_LICENSES/golang.org/x/sys/LICENSE
%license THIRD_PARTY_LICENSES/golang.org/x/text/LICENSE
%license THIRD_PARTY_LICENSES/golang.org/x/net/LICENSE
%license THIRD_PARTY_LICENSES/golang.org/x/sync/semaphore/LICENSE
%doc CONTRIBUTING.md README.md packaging/debian/changelog
%{_bindir}/*

%gopkgfiles

%changelog
* Mon Jan 25 23:45:46 UTC 2021 Eric Edens <ericedens@google.com> - 20201217.02-1
- Initial package

